// Generated by CoffeeScript 1.10.0
(function() {
  var dispXoa, displynum;

  this.displynum = displynum = function(n1) {
    return calcform.txt1.value = calcform.txt1.value + n1;
  };

  this.dispXoa = dispXoa = function(n1) {
    return calcform.txt1.value = n1;
  };

}).call(this);
