// Generated by CoffeeScript 1.10.0
(function() {
  var controller;

  controller = require('./controllers');

  module.exports = function(app) {
    return app.get('/', controller.render);
  };

}).call(this);
